### ISSUE TITLE
I can't run the project

### ISSUE THREAD

**Issue by maxsokol** [manakao/ido_2016#1]
![kohana](https://cloud.githubusercontent.com/assets/17781152/13699984/2bd9c1d0-e7a8-11e5-9e64-7a9c00795bc9.jpg)

**Comment by manakao** [comment]
try make your directory application/cache application/logs writable and if it's not exist try to create them

**Comment by maxsokol** [comment]
Thank you. Great! Worked. These folders were not, I created them. What is the username and the password of the administrator of the site, which we create?

**Comment by manakao** [comment]
admin / qwer1234
